name 'scp_sitecore_modules'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures sitecore modules'
long_description 'Installs/Configures sitecore modules'
version '1.0.0'

depends 'scp_windows'
depends 'scp_sitecore'
