name 'scp_packer_sc920_sxa190'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Sitecore 9.2.0, SPE 5.0, SXA 1.9.0'
long_description 'Installs/Configures Sitecore 9.2.0, SPE 5.0, SXA 1.9.0'
version '1.0.0'

depends 'scp_packer_w'
depends 'scp_sitecore_modules'
