require "#{File.dirname(__FILE__)}/../../../../core/chef/Berksfile.core"

scp_sources

scp_cookbook 'components', 'sitecore', 'modules'
scp_cookbook 'components', 'sitecore', 'common'
scp_cookbook 'components', 'windows'
