name 'scp_packer_solr750'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures SOLR 7.5.0'
long_description 'Installs/Configures SOLR 7.5.0'
version '1.0.0'

depends 'scp_packer_w'
depends 'scp_solr'
