include_recipe 'scp_sitecore_90x::902xp'
include_recipe 'scp_sitecore_modules::spe'
include_recipe 'scp_sitecore_modules::spe_remoting'
include_recipe 'scp_develop::debugger'
include_recipe 'scp_develop::debugger2019'
