name 'scp_solr'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures SOLR Server'
long_description 'Installs/Configures SOLR Server'
version '1.0.0'

depends 'scp_windows'
depends 'nssm', '~> 4.0.1'
