include_recipe 'scp_sitecore_91x::911xp'
include_recipe 'scp_sitecore_modules::spe'
include_recipe 'scp_sitecore_modules::spe_remoting'
include_recipe 'scp_develop::debugger'
include_recipe 'scp_develop::debugger2019'
