name 'gusztavvargadr_packer_sc90'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Packer Sitecore 9.0'
long_description 'Installs/Configures Packer Sitecore 9.0'
version '0.0.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_sitecore'
