name 'gusztavvargadr_packer_scsql16d'
maintainer 'Gusztáv Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Packer SQL Server 2016 Developer'
long_description 'Installs/Configures Packer SQL Server 2016 Developer'
version '0.0.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_sql'
