name 'scp_packer_sc902'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Packer Sitecore 9.0.2'
long_description 'Installs/Configures Packer Sitecore 9.0.2'
version '1.0.0'

depends 'scp_packer_w'
depends 'scp_sitecore'
depends 'scp_sitecore_modules'
depends 'scp_develop'
