name 'scp_packer_sc900'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Packer Sitecore 9.0'
long_description 'Installs/Configures Packer Sitecore 9.0'
version '1.0.0'

depends 'scp_packer_w'
depends 'scp_sitecore'
depends 'scp_develop'
