default['scp_commerce']['902'] = {
  'sitecore' => {
    'package_config_zip_path' => 'c:/tmp/sitecore/SIF.Sitecore.Commerce.1.2.14.zip',
    'package_config_path' => 'c:/tmp/sitecore/SIF.Sitecore.Commerce.1.2.14',
    'package_bizfx_zip_path' => 'c:/tmp/sitecore/Sitecore.BizFX.1.2.19.zip',
    'package_bizfx_path' => 'c:/tmp/sitecore/Sitecore.BizFX.1.2.19',
    'package_sdk_zip_path' => 'c:/tmp/sitecore/Sitecore.Commerce.Engine.SDK.2.2.72.zip',
    'package_sdk_path' => 'c:/tmp/sitecore/Sitecore.Commerce.Engine.SDK.2.2.72',
    'package_zip_path' => 'c:/tmp/Sitecore.Commerce.2018.07-2.2.126.zip',
    'package_url' => 'https://dev.sitecore.net/~/media/F374366CA5C649C99B09D35D5EF1BFCE.ashx',
    'package_sxa_zip_path' => 'c:/tmp/sitecore/Sitecore Experience Accelerator 1.7 rev. 180410 for 9.0.zip',
    'package_sxa_url' => 'https://dev.sitecore.net/~/media/573443081B494E2B9D83D3208B549E49.ashx',
    'package_spe_zip_path' => 'c:/tmp/sitecore/Sitecore PowerShell Extensions-4.7.2 for Sitecore 8.zip',
    'package_spe_url' => 'https://marketplace.sitecore.net/services/~/media/3D2CADDAB4A34CEFB1CFD3DD86D198D5.ashx?data=Sitecore%20PowerShell%20Extensions-4.7.2%20for%20Sitecore%208&itemId=6aaea046-83af-4ef1-ab91-87f5f9c1aa57',
    'package_nuget_zip_path' => 'c:/tmp/msbuild.microsoft.visualstudio.web.targets.14.0.0.3.nupkg',
    'package_nuget_path' => 'c:/tmp/sitecore/msbuild.microsoft.visualstudio.web.targets.14.0.0.3',
    'package_nuget_url' => 'https://www.nuget.org/api/v2/package/MSBuild.Microsoft.VisualStudio.Web.targets/14.0.0.3',
    'version' => '902',
  },
}
