name 'scp_packer_xc910'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Packer Sitecore Commerce 9.1.0'
long_description 'Installs/Configures Packer Sitecore Commerce 9.1.0'
version '1.0.0'

depends 'scp_packer_w'
depends 'scp_commerce_91x'
