name 'scp_packer_solr'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Packer SOLR 6.6.2'
long_description 'Installs/Configures Packer SOLR 6.6.2'
version '1.0.0'

depends 'scp_packer_w'
depends 'scp_solr'