require "#{File.dirname(__FILE__)}/../../../../core/chef/Berksfile.core"

gusztavvargadr_sources

gusztavvargadr_cookbook 'components', 'windows'
gusztavvargadr_cookbook 'components', 'windows', 'tests'
