name 'scp_commerce'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Sitecore Commerce'
long_description 'Installs/Configures Sitecore Commerce'
version '1.0.0'

depends 'scp_windows'
depends 'iis', '~> 6.8.0'
