default['gusztavvargadr_octopus']['tentacle'] = {
  'version' => '3.15.7',
  'execute_username' => '',
  'execute_password' => '',
  'home_directory_path' => 'C:\\Octopus',
  'communication_port' => 10_933,
  'server_web_address' => '',
  'server_web_username' => '',
  'server_web_password' => '',
  'server_api_key' => '',
  'server_communication_port' => 10_943,
  'server_thumbprint' => '',
  'node_name' => 'tentacle',
  'public_hostname' => '',
  'environment_names' => [],
  'tenant_names' => [],
  'role_names' => [],
}
