name 'scp_packer_sc902m'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Sitecore SPE SXA JSS'
long_description 'Installs/Configures SPE SXA JSS'
version '1.0.0'

depends 'scp_packer_w'
depends 'scp_sitecore_modules'
