name 'scp_packer_solr721'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Packer SOLR 7.2.1'
long_description 'Installs/Configures Packer SOLR 7.2.1'
version '1.0.0'

depends 'scp_packer_w'
depends 'scp_solr'
