name 'gusztavvargadr_packer_scsolr'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Packer SOLR 6.6.2'
long_description 'Installs/Configures Packer SOLR 6.6.2'
version '0.0.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_solr'