name 'gusztavvargadr_consul'
maintainer 'Gusztáv Varga'
maintainer_email 'me@gusztavvargadr.me'
license 'MIT'
description 'Installs/Configures Consul'
long_description 'Installs/Configures Consul'
version '0.0.0'

depends 'consul', '~> 3.0.0'
depends 'nssm', '= 3.0.0'
