---
driver:
  name: vagrant
  vagrantfiles:
    - ../../../../../../Vagrantfile.kitchen

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: w16s
    transport:
      name: winrm
    driver:
      box: scp/w16s

suites:
  - name: default
    run_list:
      - recipe[scp_virtualbox::guest_additions]
