name 'scp_packer_sc911_sxa181'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Sitecore 9.1.1, SPE 5.0, SXA 1.8.1'
long_description 'Installs/Configures Sitecore 9.1.1, SPE 5.0, SXA 1.8.1'
version '1.0.0'

depends 'scp_packer_w'
depends 'scp_sitecore_modules'
