name 'gusztavvargadr_packer_sc901'
maintainer 'Alex Smagin'
maintainer_email 'me@asmagin.com'
license 'MIT'
description 'Installs/Configures Packer Sitecore 9.0.1'
long_description 'Installs/Configures Packer Sitecore 9.0.1'
version '1.0.0'

depends 'gusztavvargadr_packer_w'
depends 'gusztavvargadr_sitecore'
depends 'gusztavvargadr_develop'
